# Generated by Django 2.1.1 on 2018-11-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0004_auto_20181108_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.FileField(upload_to='media'),
        ),
    ]
