# Generated by Django 2.1.1 on 2018-11-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0005_auto_20181108_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(upload_to='media'),
        ),
    ]
