# Generated by Django 2.1.1 on 2018-11-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0007_auto_20181108_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(default='Sin Descripcion', max_length=65),
        ),
    ]
